sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t draguljcev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true draguljcev/docker-react npm run test -- --coverage